services:
  nginx:
    build:
      context: .
      dockerfile: transcriptgenerator.client/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - dotnet-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  python-service:
    build:
      context: ./TranscriptGenerator.PythonService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./TranscriptGenerator.PythonService:/app
    environment:
      - PYTHONUNBUFFERED=1

  dotnet-server:
    build:
      context: .
      dockerfile: TranscriptGenerator.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PythonServiceUrl=http://python-service:8000
    depends_on:
      - python-service
